name: Deploy
on:
  workflow_call:
    inputs:
      appspec-name:
        default: appspec.json
        description: Name of the appspec file
        required: false
        type: string

      app-name:
        description: Name of the name e.g. patient, user, practice, gateway
        required: true
        type: string

      app-env-name:
        description: Name of the environment to deploy to e.g. risk, dev, production
        required: true
        type: string

    secrets:
      aws-access-key-id:
        description: secrets.BUILD_AWS_ACCESS_KEY_ID
        required: true

      aws-dev-build-role:
        description: secrets.OCKERS_BUILD_ROLE
        required: true

      aws-production-build-role:
        description: secrets.PRODUCTION_BUILD_ROLE
        required: true

      aws-secret-access-key:
        description: secrets.BUILD_AWS_SECRET_ACCESS_KEY
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}-beanstalk
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Determine SHA
        id: sha
        shell: pwsh
        run: |
          if($(git log -1 --pretty=%B)[0].StartsWith("chore(release)")) {
            Write-Host "::set-output name=sha::$(git rev-parse HEAD^)"
          }
          else {
            Write-Host "::set-output name=sha::${{ github.sha }}"
          }

      - name: Add AfterAllowTestTraffic Lambda
        shell: pwsh
        run: |
          $content = Get-Content "./${{ inputs.appspec-name }}" | ConvertFrom-Json

          if ($null -eq $content.Hooks) {
              Add-Member -InputObject $content -NotePropertyName "Hooks" -NotePropertyValue @()
          }

          $newHook = New-Object PSObject -Property @{ 
              "AfterAllowTestTraffic" = "${{ github.event.inputs.environment }}-common-codeDeployTestTraffic"
          }

          $content.Hooks += $newHook

          $content | ConvertTo-Json -Depth 100 | Set-Content "./${{ inputs.appspec-name }}"

      - name: Set AWS Role
        id: set-role
        uses: orthofi/actions-set-build-role@v1
        with:
          production-role: ${{ secrets.aws-production-build-role }}
          dev-role: ${{ secrets.aws-dev-build-role }}
          environment-name: ${{ inputs.app-env-name }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: us-east-1
          role-to-assume: ${{ steps.set-role.outputs.build-role }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download Task Definition
        shell: bash
        run: aws ecs describe-task-definition --task-definition ${{ inputs.app-env-name }}-${{ inputs.app-name }}-api --query taskDefinition > task-definition.json

      - name: Update Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ inputs.app-name }}-api
          image: "${{ steps.login-ecr.outputs.registry }}/${{ inputs.app-name }}-api:sha-${{ steps.sha.outputs.sha }}"
          environment-variables: |
            ASPNETCORE_ENVIRONMENT=${{ inputs.app-env-name }}
            GIT__BUILD_NUMBER=${{ github.build_number }}
            GIT__REF=${{ github.ref }}
            GIT__SHA=${{ steps.sha.outputs.sha }}
            CORECLR_ENABLE_PROFILING=1
            CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
            CORECLR_PROFILER_PATH=./datadog/linux-x64/Datadog.Trace.ClrProfiler.Native.so
            DD_DOTNET_TRACER_HOME=./datadog
            DD_ENV=${{ inputs.app-env-name }}
            DD_SERVICE=${{ inputs.app-name }}
            DD_VERSION=sha-${{ steps.sha.outputs.sha }}
            OTEL_RESOURCE_ATTRIBUTES=deployment.environment=${{ inputs.app-env-name }},service.version=sha-${{ steps.sha.outputs.sha }}

      - name: Update Docker Labels
        shell: pwsh
        run: |
          $filePath = "${{ steps.task-def.outputs.task-definition }}"

          $taskDefinition = ConvertFrom-Json($(Get-Content -Path $filePath) -join '') -AsHashtable

          $labels = $taskDefinition.containerDefinitions[0].dockerLabels

          if (-not $labels) {
              $labels = @{}
          }

          $labels["com.datadoghq.tags.version"] = "sha-${{ steps.sha.outputs.sha }}"

          ConvertTo-Json $taskDefinition -Depth 100 | Out-File $filePath

      - name: Deploy Amazon ECS Task Definition
        id: deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ inputs.app-env-name }}-${{ inputs.app-name }}-api
          cluster: ${{ inputs.app-env-name }}
          codedeploy-appspec: ${{ inputs.appspec-name }}
          codedeploy-application: ${{ inputs.app-env-name }}-${{ inputs.app-name }}-api
          codedeploy-deployment-group: ${{ inputs.app-env-name }}-${{ inputs.app-name }}-api
